- name: Install and start Deployment
  hosts: <%= hostname %>
  gather_facts: 'yes'
  vars: {}
  tasks:
    - name: Upload File to remote
      ansible.builtin.copy:
        src: >-
          <%= appDeploymentFile %>
        dest: '{{ ansible_env.HOME }}/kubesites/<%= appName %>/app-deployment.yaml'
        mode: '0755'
    - name: Execute the Update script
      become: yes
      ansible.builtin.shell: ./update.sh
      args:
        chdir: '{{ ansible_env.HOME }}/kubesites/<%= appName %>'
      environment:
        KUBECONFIG: <%= kubeconfig %>
        NVM_DIR: <%= nvmdir %>

